spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/data-jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 1000
#        one-indexed-parameters: true #page 1부터 시작이 가능해진다. 하지만, pageable 데이터랑 매칭이 안맞게 된다. (권장 x)
        #default -> page size : 20, max page size : 2000

  h2:
    console.enabled: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace